### ISSUE TITLE
Create full typescript solution, including VM, pods...

### ISSUE THREAD

**Issue by brauliodiez** [Lemoncode/redux-chat-front#35]
Start this right after the JS full redux has been completed.

Before start with this solution we will need to have a discussion, I will send you a folder proposal.

- It will include viewmodels + mappers
- It will include pods (we will send you in an email a folder proposal).
- ...

No readme on this sample, it will let us show the benefits of havig a full fledged arhicture.

**Comment by fjcalzado** [comment]
Done #48  and #49
