### ISSUE TITLE
Possible typo in Readme?

### ISSUE THREAD

**Issue by adriancorcoran** [Lemoncode/redux-chat-front#58]
Hey Guys - just flagging this as a possible typo for you for the future :)

In this file - https://github.com/Lemoncode/redux-chat-front/tree/master/01_ES6/02_redux_sync_action

near the end

![](https://screenshot.click/13-48-pxe3w-ypf7w.jpg)

**Comment by brauliodiez** [comment]
Thanks a lot for reporting this issue, it will help other mates following the step by step guide.

I have just apply the fix you mentioned and merged the branch.
